export const URLS = {
    sign_in: 'api/auth/sign-in',
    category_get_all: '/api/category/get-all',
    category_get_one: '/api/category/get-by-id',
    category_add: '/api/category/add',
    category_delete: '/api/category/delete',
    category_edit: '/api/category/edit',
    market_get_all: '/api/market/get-all',
    market_get_one: '/api/market/get-by-id',
    market_add: '/api/market/add',
    market_delete: '/api/market/delete',
    market_edit: '/api/market/edit',
    product_get_all: '/api/product/get-all',
    product_get_one: '/api/product/get-by-id',
    product_add: '/api/product/add',
    product_delete: '/api/product/delete',
    product_edit: '/api/product/edit',
    translations_list: '/api/lang/all',
    translations_edit: '/api/lang/create-edit',
    user_get_all: '/api/user/get-all',
    user_block: '/api/user/block',
    user_unblock: '/api/user/unblock',
    user_one: '/api/user/get-by-id',
    file_upload: '/api/files/upload',
    get_order: '/api/order/get',
    delivered_order: '/api/order/delivered',
};
